import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Are European citizens still trusting public television and radio networks?",
  "subtitle": "In 2023 on average 48% of the interviewed EU citizens tend to trust the public media.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nBelgium,BE,0.56,false,,,,,,,,,\nBulgaria,BG,0.49,false,,,,,,,,,\nCzechia,CZ,0.45,false,,,,,,,,,\nDenmark,DK,0.61,false,,,,,,,,,\nGermany,DE,0.54,false,,,,,,,,,\nEstonia,EE,0.59,false,,,,,,,,,\nIreland,IE,0.56,false,,,,,,,,,\nGreece,EL,0.39,false,,,,,,,,,\nSpain,ES,0.48,false,,,,,,,,,\nFrance,FR,0.46,false,,,,,,,,,\nCroatia,HR,0.46,false,,,,,,,,,\nItaly,IT,0.45,false,,,,,,,,,\nCyprus,CY,0.45,false,,,,,,,,,\nLatvia,LV,0.50,false,,,,,,,,,\nLithuania,LT,0.54,false,,,,,,,,,\nLuxembourg,LU,0.59,false,,,,,,,,,\nHungary,HU,0.25,false,,,,,,,,,\nMalta,MT,0.39,false,,,,,,,,,\nNetherlands,NL,0.60,false,,,,,,,,,\nAustria,AT,0.50,false,,,,,,,,,\nPoland,PL,0.26,false,,,,,,,,,\nPortugal,PT,0.65,false,,,,,,,,,\nRomania,RO,0.43,false,,,,,,,,,\nSlovenia,SI,0.48,false,,,,,,,,,\nSlovakia,SK,0.46,false,,,,,,,,,\nFinland,FI,0.71,false,,,,,,,,,\nSweden,SE,0.63,false,,,,,,,,,",
  "parsedData": [
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.56,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.49,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.45,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.61,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.54,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.59,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.56,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.39,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.48,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.46,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.46,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.45,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.45,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.5,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.54,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.59,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.25,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.39,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.6,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.5,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.26,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.65,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.43,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.48,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.46,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.71,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.63,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "blue",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurobarometer (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "The survey was conducted via computer-assisted web interviewing (CAWI) using Ipsos online panels and partner networks, with some respondents additionally recruited through social media. Fieldwork took place from 18 to 24 October 2023 among EU citizens aged 15+ across the EU27, with 25,956 total interviews.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://europa.eu/eurobarometer/surveys/detail/3153",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Are European citizens still trusting public television and radio networks?",
    "subtitle": "In 2023 on average 48% of the interviewed EU citizens tend to trust the public media.",
    "textNoteDescription": "Note",
    "textNote": "The survey was conducted via computer-assisted web interviewing (CAWI) using Ipsos online panels and partner networks, with some respondents additionally recruited through social media. Fieldwork took place from 18 to 24 October 2023 among EU citizens aged 15+ across the EU27, with 25,956 total interviews.",
    "textSourceDescription": "Source",
    "textSource": "Eurobarometer (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here"
  },
  "clusters": [],
  "colorScale": null
});